### ISSUE TITLE
"Error in first stage of winmin-setup command"

### ISSUE THREAD

**Issue by ItsMaddieNow** [vlinkz/winmin-instructions#2]
```mario-whitmore@pop-os:~$ winmin-setup
Gtk-Message: 20:53:36.121: Failed to load module "appmenu-gtk-module"

(winmin-setup:23640): Gtk-WARNING **: 20:53:36.339: Could not find signal handler 'on_stack_configure_event'.  Did you compile with -rdynamic?
ISOPATH: /home/mario-whitmore/Documents/Win10_2004_English_Custom_x64.iso
ERROR    Error: --disk /tmp/virtio-win.iso,device=cdrom: Could not start storage pool: cannot stat file '/tmp/.mount_UnityH0GDYbs': Permission denied
error: failed to get domain 'winmin-base'
NULL```
I'm on Pop OS 20.04 and installed the .deb files from the releases page if that matters

**Comment by vlinkz** [comment]
Seems similar to a problem faced here: https://github.com/jedi4ever/veewee/issues/996#issuecomment-59161407
If that solution doesn't work, please let me know.

**Comment by ItsMaddieNow** [comment]
Unfortunately, it didn't work and it threw the same error.

**Comment by vlinkz** [comment]
Try installing `virt-manager` and seeing if a VM named `winmin-base` exists. If so, delete it. Also, look in `/var/lib/libvirt/images` as root and delete `winmin-base.img`.
If that doesn't work, can you send the output of `ls -l /tmp/.mount_UnityH0GDYbs`?

**Comment by ItsMaddieNow** [comment]
Thanks that worked.
Thank you for your help.
